apiVersion: v1
kind: Service
metadata:
  name: brain
  namespace: bakerst
spec:
  type: NodePort
  selector:
    app: brain
    slot: blue
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      name: http
