apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bakerst

resources:
  - namespace.yaml
  - nats
  - qdrant
  - brain
  - task
  - worker
  - ui
  - gateway
  - sysadmin
  - network-policies.yaml
