apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: bakerst
  labels:
    app: nats
data:
  nats.conf: |
    listen: 0.0.0.0:4222

    jetstream {
      store_dir: /data/jetstream
      max_mem: 128M
      max_file: 512M
    }
