apiVersion: v1
kind: Service
metadata:
  name: sysadmin
  namespace: bakerst
spec:
  type: NodePort
  selector:
    app: sysadmin
  ports:
    - port: 3090
      targetPort: 3090
      nodePort: 30090
      name: http
